kind: ConfigMap
apiVersion: v1
metadata:
  name: hivems-hadoop-metastore
  namespace: hive-metastore
  labels:
    app.kubernetes.io/instance: hivems
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hive-metastore
    app.kubernetes.io/part-of: hive-metastore
    app.kubernetes.io/version: 2.3.6
    helm.sh/chart: hive-metastore-0.1.3
  annotations:
    meta.helm.sh/release-name: hivems
    meta.helm.sh/release-namespace: hive-metastore
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:core-site.xml: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>

    <property>
      <name>fs.s3a.connection.ssl.enabled</name>
      <value>false</value>
    </property>
     
    <property>
      <name>fs.s3a.endpoint</name>
      <value>http://192.168.64.5:9000</value>
    </property>
     
    <property>
      <name>fs.s3a.access.key</name>
      <value>1uBoa5gtgiSm8DQ8JOyB</value>
    </property>
     
    <property>
      <name>fs.s3a.secret.key</name>
      <value>9irs4ZoYSKDORxbb9zQpX9sbdbXioSAEZSdsq6GK</value>
    </property>
     
    <property>
      <name>fs.s3a.path.style.access</name>
      <value>true</value>
    </property>
     
    <property>
      <name>fs.s3a.impl</name>
      <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
    </property>

    </configuration>
