kind: Secret
apiVersion: v1
metadata:
  name: hivems-postgresql
  namespace: hive-metastore
  labels:
    app.kubernetes.io/instance: hivems
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.2.8
  annotations:
    meta.helm.sh/release-name: hivems
    meta.helm.sh/release-namespace: hive-metastore
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:postgresql-password: {}
          f:postgresql-postgres-password: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
        f:type: {}
data:
  postgresql-password: aGl2ZQ==
  postgresql-postgres-password: UXl3RmVvUEJlYQ==
type: Opaque
