kind: Service
apiVersion: v1
metadata:
  name: hivems-hive-metastore
  namespace: hive-metastore
  labels:
    app.kubernetes.io/component: metastore
    app.kubernetes.io/instance: hivems
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hive-metastore
    app.kubernetes.io/part-of: hive-metastore
    app.kubernetes.io/version: 2.3.6
    helm.sh/chart: hive-metastore-0.1.3
  annotations:
    meta.helm.sh/release-name: hivems
    meta.helm.sh/release-namespace: hive-metastore
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":9083,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
    - manager: dashboard
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:externalIPs: {}
          f:ports:
            k:{"port":10000,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":10001,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":10502,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
spec:
  ports:
    - name: thrift
      protocol: TCP
      port: 9083
      targetPort: 9083
    - name: hive2
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: hive22
      protocol: TCP
      port: 10001
      targetPort: 10001
    - name: hive222
      protocol: TCP
      port: 10002
      targetPort: 10002
  selector:
    app.kubernetes.io/component: metastore
    app.kubernetes.io/instance: hivems
    app.kubernetes.io/name: hive-metastore
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}
