kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: hivems-hive-metastore
  namespace: hive-metastore
  labels:
    app.kubernetes.io/component: metastore
    app.kubernetes.io/instance: hivems
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hive-metastore
    app.kubernetes.io/part-of: hive-metastore
    app.kubernetes.io/version: 2.3.6
    helm.sh/chart: hive-metastore-0.1.3
  annotations:
    meta.helm.sh/release-name: hivems
    meta.helm.sh/release-namespace: hive-metastore
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          f:persistentVolumeClaimRetentionPolicy:
            .: {}
            f:whenDeleted: {}
            f:whenScaled: {}
          f:podManagementPolicy: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:serviceName: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app.kubernetes.io/component: {}
                f:app.kubernetes.io/instance: {}
                f:app.kubernetes.io/name: {}
            f:spec:
              f:containers:
                k:{"name":"metastore"}:
                  .: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"hive-config"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
          f:updateStrategy:
            f:rollingUpdate:
              .: {}
              f:partition: {}
            f:type: {}
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:spec:
              f:containers:
                k:{"name":"metastore"}:
                  f:command: {}
                  f:image: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/opt/hadoop-3.2.3/etc/hadoop"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/opt/hadoop-3.2.3/share/hadoop/hdfs/lib"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/opt/hive/conf"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:volumes:
                k:{"name":"hadoop-config"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
                k:{"name":"hostpath-volume"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-03-05T14:16:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:availableReplicas: {}
          f:collisionCount: {}
          f:currentReplicas: {}
          f:currentRevision: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updateRevision: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: metastore
      app.kubernetes.io/instance: hivems
      app.kubernetes.io/name: hive-metastore
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: metastore
        app.kubernetes.io/instance: hivems
        app.kubernetes.io/name: hive-metastore
    spec:
      volumes:
        - name: hive-config
          configMap:
            name: hivems-hive-metastore
            defaultMode: 420
        - name: hadoop-config
          configMap:
            name: hivems-hadoop-metastore
            defaultMode: 420
      containers:
        - name: metastore
          image: 5200710/hive:3.1.3-postgresql-metastore
          command:
            - /bin/sh
            - '-c'
            - >-
              /opt/hive/bin/hive --service metastore --hiveconf
              hive.root.logger=INFO,console & /opt/hive/bin/hive --service
              hiveserver2 --hiveconf hive.server2.thrift.port=10000 --hiveconf
              hive.root.logger=INFO,console
          resources: {}
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf
            - name: hadoop-config
              mountPath: /opt/hadoop-3.2.3/etc/hadoop
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: hivems-hive-metastore
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
status:
  observedGeneration: 24
  replicas: 2
  readyReplicas: 2
  currentReplicas: 2
  updatedReplicas: 2
  currentRevision: hivems-hive-metastore-559fc4b46c
  updateRevision: hivems-hive-metastore-559fc4b46c
  collisionCount: 0
  availableReplicas: 2
